import React from "react";
import ReactDOM from "react-dom";
import Chat from "./components/ChatRoom/ChatRoom.jsx";
import Calendar from "./components/ADMIN/Calendar/Calendar.jsx";
import DeleteCohortOrUsers from "./components/ADMIN/DeleteCohortOrUsers/DeleteCohortOrUsers.jsx";
import App from "./components/App/App.jsx";
import ChatRoom from "./components/ChatRoom/ChatRoom.jsx";
import UserPorfileADMIN from "./components/ADMIN/UserProfile/UserProfile.jsx";
import CreateAccount from "./components/ADMIN/CreateAccount/CreateAccount.jsx";
import UserProfile from "./components/User/UserProfile/UserProfile.jsx";
import UserNavbar from "./components/User/UserNavbar/UserNavbar.jsx";
ReactDOM.render(<UserNavbar />, document.getElementById("app"));
